### ISSUE TITLE
[docs] Specify in documentation what versions of Outlook that the plugin is compatible with

### ISSUE THREAD

**Issue by lfvjimisola** [diggsweden/jitsi-outlook#21]
### Contact Details

LFV

### What benefits does the suggestion solve?

Allows users to know if the plugin is compatible with their version of Outlook

### Feature suggestion description

Add part in the document on compatibility with Outlook versions.

**Comment by Ayko1595** [comment]
Hi! Thank you for creating this issue. I will add the supported versions into the README 😊

**Comment by lfvjimisola** [comment]
When do you think that you can provide the information?

**Comment by Ayko1595** [comment]
@lfvjimisola  Sorry for the delay. The relevant information has now been merged into the main repository
