### ISSUE TITLE
Make font family configurable via config.json

### ISSUE THREAD

**Issue by stallberg** [diggsweden/jitsi-outlook#41]
### Contact Details

tallberg.sebastian@gmail.com

### What benefits does the suggestion solve?

Gives the user the ability to configure the font of the plugin text to their liking.

### Feature suggestion description

Implement configurable font family via `config.json` while defaulting to Arial (current font family used) if nothing is explicitly configured.

Requires a couple lines of changes in [DOMHelper.ts](https://github.com/diggsweden/jitsi-outlook/blob/main/src/utils/DOMHelper.ts) and [Config.ts](https://github.com/diggsweden/jitsi-outlook/blob/main/src/models/Config.ts), as well as updating the `config.json` section of the `README`.

**Comment by Ayko1595** [comment]
Sounds good! :-)
