### ISSUE TITLE
[Question] Installation

### ISSUE THREAD

**Issue by lfvjimisola** [diggsweden/jitsi-outlook#43]
### What happened?

This is not a bug per se but rather a question for our provider, CGI.

I've asked question in the community forum without luck. 

From our provider, CGI,
Det verkar som vi stött på lite patrull med denna paketering.
 
Denna https://github.com/diggsweden/jitsi-outlook, som ni önskar, går tydligen inte att installera på klientdator som addin för Outlook.

Om man läser i ovan länk och denna [https://learn.microsoft.com/en-us/office/dev/add-ins/publish/publish] så ser det ut som att jitsi addin kan installeras på ett av följande sätt:
* Installera jitsi addin på Exchange Server för alla användare eller utvalda
* Publicera jitsi addin på en webserver (OWA kanske fungerar) och sen får varje användare som ska använda denna själv installera den via inlogg i Web Outlook (OWA).
* Annat??
 
Det är dock fortfarande osäkert om något av alternativen kommer göra så att jitsi addin går att lägga in i er Outlook klient på datorn.
 
Jag såg i någon diskussion att teknikerna fått JitsiMeetOutlook-v0.7.0-windows-anycpu.msi att fungera med lite ändringar i konfig fil (installations parametrar) men för att göra den sista justeringen så måste LFV sätta upp/lägga till saker på serversidan (jitsi.lfv.se)
Jag förstår dock att det är DIGG-versionen (ovan) ni vill använda och det verkar inte fungera.
 
Har ni någon kontakt med andra myndigheter som använder denna och kan få någon fingervisning om hur de använder/installerar DIGG-versionen?

### Steps To Reproduce

N/A

### What did you expect?

N/A

### Version

latest

**Comment by small1** [comment]
Den där installeras på exchange. Den ska inte ut på klienten alls.

Skicka mail till mig på johan.bernhardsson@redpill-linpro.com. så kan jag skicka en översikt över hur det fungerar.

**Comment by small1** [comment]
Den dom paketerat är från ett helt annat projekt (när jag ser versions nummer)

**Comment by lfvjimisola** [comment]
> Den dom paketerat är från ett helt annat projekt (när jag ser versions nummer)

Om du syftar på "JitsiMeetOutlook-v0.7.0-windows-anycpu.msi" så stämmer det. Dom provade denna efter ha försökt med DIGG:s utan framgång.

Jag utgår från att vi inte är dom enda som kan tänkas ha/få detta problemet. Är det inte bättre att ni dokumenterar här i projektet på github hur det fungerar så att andra kan ta del av samma information?

Jag ber dom kontakta dig direkt.

**Comment by jimisola** [comment]
@Ayko1595 FYI, our IT supplier haven't been able install it yet. They're hoping that lunch webinar will help them.

**Comment by Ayko1595** [comment]
@jimisola I apologise for closing the issue if it has not been solved already. I thought this was taken outside of GitHub. Maybe they could email me directly at konstantin.ay@intunio.se
